export const AsyncStatus = {
  IDLE: 'IDLE',
  LOADING: 'LOADING',
  SUCCESS: 'SUCCESS',
  FAILED: 'FAILED'
}

export const UserActions = {
  USER_LOGIN: 'USER_LOGIN',
  USER_UPDATE: 'USER_UPDATE',
  USER_DELETE: 'USER_DELETE',
  USER_REGISTER: 'USER_REGISTER',
  USER_LOGOUT: 'USER_LOGOUT',
  USER_CHECK_TOKEN: 'USER_CHECK_TOKEN',
  USER_CHANGE_PASSWORD: 'USER_CHANGE_PASSWORD'
}

export const CountryActions = {
  COUNTRY_GETALL: 'COUNTRY_GETALL'
}
